main: io.github.siebrenvde.staffchat.Main
name: StaffChat
description: Simple Spicord staffchat plugin
author: Siebrenvde
version: 1.2
depend: [Spicord]

commands:
  staffchat:
    aliases: [sc, schat, staffc]
    description: Chat with other staff members
  report:
    description: Report players
  helpop:
    aliases: [ho, helpo, hop]
    description: Ask staff for help