main: io.github.siebrenvde.staffchat.Main
name: StaffChat
description: Simple Spicord staffchat plugin
author: Siebrenvde
version: 1.0
depend: [Spicord]

commands:
  staffchat:
    aliases: [sc, schat, staffc]
    description: Send a message to online staff